### ISSUE TITLE
【Certificate inspection】查验请求

### ISSUE THREAD

**Issue by Candicepan** [Awesome-DeepLearning/CertificateInspection#10]
# 证书自助查验系统
如需查验证书与持有人是否匹配，可按下方提示对`N0000000`、`ZhangSan`等字段进行修改，提交成功后将会在1~5分钟内返回由@GT-ZhangAcer提供的校验结果，请辨别校验结果来源。

### 证书编号 - Certificate ID  

-+-+-+-
H2021111199
-+-+-+-

### 证书持有者姓名 - Certificate Holders  

-+-+-+-
潘潘
-+-+-+- 

### [可选]附加信息

-+-+-+-
无
-+-+-+-

### [可选]校验码 - Check code  

-+-+-+-
AHSJKDHQIWNWINDI
-+-+-+-

**Comment by GT-ZhangAcer** [comment]
# PaddlePaddle Hackathon 2021飞桨黑客马拉松48H Coding Party获奖项目  
# 获奖项目证书持有人验证报告  
亲爱的@Candicepan，  
    您的电子版证书如下：
    ![](https://ai-studio-static-online.cdn.bcebos.com/b97c9038383e44bc84133b6c3317ceae2328de8b1b664022b3adda002fba0ca0)
    该证书来源于PaddlePaddle Hackathon 2021飞桨黑客马拉松48H Coding Party获奖项目，与您提供的持有者信息相匹配！  
  
## 相关信息如下  
  
证书编号：H2021111199  
证书名称：测试员老张  
  
-+-+-+-+-+-+-+-+-+-+-+-+-  
Tips：每年都会有进行PaddlePaddle Hackathon 飞桨黑客马拉松活动，若您喜欢飞桨开源社区，无论是`仓库贡献`、`代码贡献`、`用Star等方式鼓励其他优秀开发者作品`等，我们欢迎您的加入，PaddlePaddleHackathon官方交流群[343734965](https://jq.qq.com/?_wv=1027&k=OUgKABSv)，期待与您一同建设飞桨开源社区。
