### ISSUE TITLE
【Certificate inspection】查验请求

### ISSUE THREAD

**Issue by jhcgt4869** [Awesome-DeepLearning/CertificateInspection#6]
# 证书自助查验系统
如需查验证书与持有人是否匹配，可按下方提示对`N0000000`、`ZhangSan`等字段进行修改，提交成功后将会在1~5分钟内返回由@GT-ZhangAcer提供的校验结果，请辨别校验结果来源。

## 证书编号 - Certificate ID
----------
A202112W2025
----------
## 证书持有者姓名 - Certificate Holders
----------
项建彪
----------
## [可选]附加信息
----------
无
----------
## [可选]校验码 - Check code
----------
AHSJKDHQIWNWINDI
----------

**Comment by GT-ZhangAcer** [comment]
# WAVE SUMMIT+2021最受欢迎开发者开源项目秋季评选证书持有人验证报告  
亲爱的@jhcgt4869，  
    该证书来源于WAVE SUMMIT+2021最受欢迎开发者开源项目秋季评选，与您提供的持有者信息相匹配！  
  
## 相关信息如下  
证书编号：A202112W2025  
证书名称：开源共建者  
--------------------  
Tips：在每年的上半年与下半年，都会有一场WAVE SUMMIT最受欢迎开发者开源项目评选，若您喜欢飞桨开源社区，无论是`仓库贡献`、`代码贡献`、`用Star等方式鼓励其他优秀开发者作品`等均可参与评选，评选官方交流群[837151052](https://jq.qq.com/?_wv=1027&k=OUgKABSv)，期待与您一同建设开源社区。
